name: .NET Core

on:
  pull_request:
    branches: [ master ]
    paths: 
      - "C#/**"
      - "!C#/MK94.Dumper/nuget.version"
      
jobs:
  build:
    defaults:
      run:
        working-directory: C#

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
          node-version: '12'

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Client/**/package-lock.json') }}
        
    - name: Cache Client
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: C#/MK94.Dumper/Client
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Client/**') }}
        
    - name: Cache nuget packages
      uses: actions/cache@v2
      env:
        cache-name: cache-nuget-packages
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('C#/**.csproj') }}
        
    - name: Setup Yarn
      run: npm install -g yarn
      
    - name: Yarn install
      working-directory: Client
      run: yarn

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
