name: Publish Nuget

on:
  push:
    branches: [ master ]
    paths: C#/MK94.SeeRaw/nuget.version

jobs:
  publish:
    defaults:
      run:
        working-directory: C#/MK94.SeeRaw
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
          node-version: '12'

    - name: Setup Yarn
      run: npm install -g yarn
      
    - name: Yarn install
      working-directory: Client
      run: yarn

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Pack
      run: | 
        version="`cat nuget.version`"
        dotnet pack --configuration Release --no-restore /p:Version=$version

    - name: Publish
      run: | 
        version="`cat nuget.version`" 
        cd bin/Release
        dotnet nuget push MK94.SeeRaw.$version.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
